{
    // relative imports raises exception in python
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Curr File",
            "type": "debugpy",
            "request": "launch",
            "program": "${workspaceFolder}/src/cumind/__main__.py",
            "console": "integratedTerminal"
        },
        {
            "name": "CuMind",
            "type": "debugpy",
            "request": "launch",
            "module": "cumind",
            "args": [
                "--config",
                "test.json"
            ],
        }
    ]
}