{
    // relative imports raises exception in python
    "version": "0.2.0",
    "configurations": [
        {
            "name": "cartpole",
            "type": "debugpy",
            "request": "launch",
            "program": "${workspaceFolder}/src/cartpole.py",
            "console": "integratedTerminal",
            "stopOnEntry": true
        },
        {
            "name": "CuMind",
            "type": "debugpy",
            "request": "launch",
            "module": "cumind",
            "args": [
                "--config",
                "test.json"
            ],
        }
    ]
}